export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLE_LIST = 'FILTER_ARTICLE_LIST'

export const FILTER_ARTICLE_LIST_BY_ID = 'FILTER_ARTICLE_LIST'

export const FILTER_ARTICLE_LIST_BY_DATE_RANGE = 'FILTER_ARTICLE_LIST_BY_DATE_RANGE'
